pool:
  vmImage: 'Ubuntu 16.04'
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'curl https://raw.githubusercontent.com/Azure/batchexplorer/master/python/requirements.txt -o runner/berequirements.txt'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7.x'
    addToPath: true
    architecture: 'x64'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'python -m pip install merge-requirements'
- task: Bash@3
  inputs:
    workingDirectory: 'runner'
    targetType: 'inline'
    script:
      python -m merge_requirements.main berequirements.txt requirements.txt
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true
    OverWrite: true
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: batch-extension-templates
